# KnightyApp Docker Compose
# For local development and testing

version: '3.8'

services:
  knightyapp:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=development
      - NEWSLETTER_API_URL=${NEWSLETTER_API_URL:-http://pocketbase-wo0s48c8g8w4gcocgc4ks0kc.45.76.250.233.sslip.io/api/collections/cli_newsletters/records}
      - NEWSLETTER_API_TOKEN=${NEWSLETTER_API_TOKEN:-your_token_here}
    volumes:
      # Mount cheatsheets for development
      - ./public/htmls:/app/public/htmls:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.knightyapp.service=cheatsheets"
      - "com.knightyapp.version=1.0.0"

  # Optional: Nginx reverse proxy for production-like setup
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - knightyapp
    restart: unless-stopped
    profiles:
      - "production"

networks:
  default:
    name: knightyapp-network

