[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_ENV = "production"
  CI = "false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/htmls/*"
  to = "/htmls/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3000
  publish = "build"


