# KnightyApp - React + Go deployment

[phases.setup]
nixPkgs = ["nodejs_18", "go_1_21"]

[phases.install]
cmds = [
    "npm config set registry https://registry.npmjs.org/",
    "npm ci --production --retry=3 --fetch-timeout=60000 --maxsockets=1",
]

[phases.build]
cmds = [
    "npm run build",
    "cp -r build/* ./",
    "mkdir -p htmls",
    "cp -r public/htmls/* ./htmls/ || true",
    "go build -o main main.go",
]

[start]
cmd = "./main"
