# Clean Nixpacks for KnightyApp - Simple Go + React deployment

[phases.setup]
nixPkgs = ["nodejs_18", "go_1_21"]

[phases.install]
cmds = ["npm ci --production"]

[phases.build]
cmds = [
    "npm run build",
    "cp -r build/* ./",
    "mkdir -p htmls",
    "cp -r public/htmls/* ./htmls/ || true",
    "go build -o main main.go"
]

[start]
cmd = "./main"
