# Alternative Nixpacks configuration for Dokploy
# More explicit about file paths and error handling

[phases.setup]
nixPkgs = ["nodejs_18", "go_1_21", "git", "curl"]

[phases.install]
cmds = [
    "echo 'Current directory:' && pwd",
    "echo 'Files in directory:' && ls -la",
    "echo 'Installing Node.js dependencies...'",
    "npm ci --only=production --no-audit --no-fund",
    "echo 'Dependencies installed successfully'",
]

[phases.build]
cmds = [
    "echo 'Starting build process...'",
    "echo 'Current directory:' && pwd && ls -la",

    # React build
    "echo '=== Building React Frontend ==='",
    "CI=false npm run build",
    "echo 'React build completed. Checking build directory:'",
    "ls -la build/ || echo 'Build directory not found'",

    # Copy React files
    "echo '=== Copying React Build Files ==='",
    "cp -r build/* ./ && echo 'React files copied' || echo 'Failed to copy React files'",
    "ls -la *.html *.js *.css static/ || echo 'Some files missing'",

    # Copy HTML cheat sheets  
    "echo '=== Copying HTML Cheat Sheets ==='",
    "mkdir -p htmls",
    "if [ -d 'public/htmls' ]; then cp -r public/htmls/* ./htmls/ && echo 'HTML files copied'; else echo 'No htmls directory found'; fi",
    "ls -la htmls/ || echo 'htmls directory empty or missing'",

    # Go build
    "echo '=== Building Go Application ==='",
    "echo 'Go version:' && go version",
    "go mod download && echo 'Go modules downloaded'",
    "go mod verify && echo 'Go modules verified'",
    "CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags='-w -s' -o main *.go",
    "echo 'Go build completed. Checking binary:'",
    "ls -la main && file main",

    # Final verification
    "echo '=== Final Verification ==='",
    "echo 'All files in root directory:'",
    "ls -la",
    "echo 'Required files check:'",
    "test -f main && echo '✅ main binary exists' || echo '❌ main binary missing'",
    "test -f index.html && echo '✅ index.html exists' || echo '❌ index.html missing'",
    "test -d htmls && echo '✅ htmls directory exists' || echo '❌ htmls directory missing'",
    "test -d static && echo '✅ static directory exists' || echo '❌ static directory missing'",
    "echo 'Build process completed successfully!'",
]

[start]
cmd = "./main"

[variables]
PORT = "8080"
NODE_ENV = "production"
GO111MODULE = "on"


