# Simplified Nixpacks for KnightyApp - Focus on Go deployment only
# React build will be handled separately

[phases.setup]
nixPkgs = ["nodejs_18", "go_1_21"]

[phases.install]
cmds = ["npm ci --production"]

[phases.build]
cmds = [
    "npm run build",
    "cp -r build/* ./",
    "mkdir -p htmls",
    "cp -r public/htmls/* ./htmls/ || true",
    "cp go.simple.mod go.mod",
    "go build -o main main.simple.go",
]

[start]
cmd = "./main"
