# Debug nixpacks for Dokploy - explicit paths

[variables]
GO_VERSION = "1.21"

[phases.setup]
nixPkgs = ["go_1_21"]

[phases.build]
cmds = [
    "echo 'Current directory:' && pwd",
    "echo 'Files in directory:' && ls -la",
    "echo 'Building Go app...'",
    "go mod tidy || echo 'No go.mod changes needed'",
    "go build -v -o main main.minimal.go",
    "echo 'Build completed, checking binary:'",
    "ls -la main && file main"
]

[start]
cmd = "./main"
